services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - epi-network

  solr:
    image: solr:9.9
    container_name: episciences-solr
    ports:
      - "8983:8983"
    networks:
      - epi-network
    environment:
      ZK_HOST: "episciences-zoo:2181"
      SOLR_MODULES: "analysis-extras"
    depends_on:
      - zoo
    volumes:
      - solr_data:/var/solr
      - type: bind
        source: ./solr
        target: /opt/configsets
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solr.rule=Host(`solr.episciences.org`)"
      - "traefik.http.routers.solr.entrypoints=web"
      - "traefik.http.routers.solr-secure.rule=Host(`solr.episciences.org`)"
      - "traefik.http.routers.solr-secure.entrypoints=websecure"
      - "traefik.http.routers.solr-secure.tls=true"
      - "traefik.http.services.solr.loadbalancer.server.port=8983"

  zoo:
    image: zookeeper:3.9
    container_name: episciences-zoo
    networks:
      - epi-network
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

  db-episciences:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: 'episciences-db-episciences'
    expose:
      - "3306"
    ports:
      - "33060:3306"
    volumes:
      - mysql-db-episciences:/var/lib/mysql
      - type: bind
        source: ./mysql/episciences/episciences.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: ./mysql/episciences/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    env_file:
      - mysql/episciences/mysql.env
    networks:
      - epi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db-indexing:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: 'episciences-db-indexing'
    expose:
      - "3306"
    ports:
      - "33061:3306"
    volumes:
      - mysql-db-indexing:/var/lib/mysql
      - type: bind
        source: ./mysql/solr/solr_index_queue.sql
        target: /docker-entrypoint-initdb.d/init.sql
    env_file:
      - mysql/solr/mysql.env
    networks:
      - epi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db-auth:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: 'episciences-db-auth'
    expose:
      - "3306"
    ports:
      - "33062:3306"
    volumes:
      - mysql-db-auth:/var/lib/mysql
      - type: bind
        source: ./mysql/auth/cas_users.sql
        target: /docker-entrypoint-initdb.d/init.sql
    env_file:
      - mysql/auth/mysql.env
    networks:
      - epi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  epi-citations-db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: 'episciences-db-citations'
    expose:
      - "3306"
    ports:
      - "33063:3306"
    volumes:
      - mysql-db-citations:/var/lib/mysql
      - type: bind
        source: ./mysql/citations/citations.sql
        target: /docker-entrypoint-initdb.d/init.sql
    env_file:
      - mysql/citations/mysql.env
    networks:
      - epi-network


  pma:
    container_name: 'episciences-db-phpmyadmin'
    image: "phpmyadmin:latest"
    environment:
      - "PMA_PMADB=pma"
      - "PMA_CONTROLUSER=root"
      - "PMA_CONTROLPASS=root"
      - "PMA_QUERYHISTORYDB=true"
      - "PMA_USER=root"
      - "PMA_PASSWORD=root"
      - "PMA_ARBITRARY=1"
      - "PMA_HOSTS=episciences-db-episciences,episciences-db-indexing,episciences-db-auth,episciences-db-citations"
      - "PMA_VERBOSES=episciences,indexing,auth,citations"
      - "UPLOAD_LIMIT=2G"
      - "MEMORY_LIMIT=1G"
    ports:
      - "8001:80"
    depends_on:
      - db-episciences
      - db-indexing
      - db-auth
    networks:
      - epi-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.episciences.org`)"
      - "traefik.http.routers.pma.entrypoints=web"
      - "traefik.http.routers.pma-secure.rule=Host(`pma.episciences.org`)"
      - "traefik.http.routers.pma-secure.entrypoints=websecure"
      - "traefik.http.routers.pma-secure.tls=true"
      - "traefik.http.services.pma.loadbalancer.server.port=80"

networks:
  epi-network:
    name: epi-network
    driver: bridge

volumes:
  mysql-db-episciences:
  mysql-db-indexing:
  mysql-db-auth:
  mysql-db-citations:
  solr_data:

